# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCitationCFF: false
AddCodeOfConduct: false
AddCompatHelperCI: true
AddContributionDocs: false
AddCopierCI: false
AddDependabot: true
AddDocs: true
AddDocsCI: true
AddFormatterAndLinterConfigFiles: true
AddGitHubPRTemplate: false
AddGitHubTemplates: false
AddLintCI: false
AddLychee: false
AddMacToCI: false
AddPrecommit: false
AddTagBotCI: true
AddTestCI: true
AddWinToCI: false
Authors: xuanzhe xia <hzxiaxz@gmail.com>
CheckExplicitImports: false
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinCIVersion: lts
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: xuanzhe xia
MarkdownIndentation: 2
PackageName: NCPseudoGen
PackageOwner: hz-xiaxz
PackageUUID: d223997f-89d2-5956-bc8f-a0eaec0594e6
RunJuliaNightlyOnCI: false
StrategyConfirmIncluded: true
StrategyLevel: 1
StrategyReviewExcluded: false
TestingStrategy: basic_auto_discover
UseCirrusCI: false
_src_path: /home/hzxiaxz/.julia/packages/BestieTemplate/6JtNK
